all:	danielj_project3_partA.cpp danielj_project3_partB.cpp danielj_project3_partC.cpp
		
	g++ -o project3_A danielj_project3_partA.cpp
	g++ -o project3_B danielj_project3_partB.cpp
	g++ -o project3_C danielj_project3_partC.cpp
